<?xml version="1.0"?>
<package format="3">
  <name>llm_voice_agent</name>
  <version>0.0.1</version>
  <description>Voice dialog agent that bridges speech -> LLM -> text topics</description>
  <maintainer email="you@example.com">sundasheng</maintainer>
  <license>BSD</license>

  <!-- 只要 ament_python，不要 ament_cmake -->
  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>

