map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: /home/sundasheng/ros2_ws/maps/home_map_clean_02_260705.yaml


amcl:
  ros__parameters:

    use_sim_time: false

    scan_topic: /scan

    base_frame_id: base_footprint
    odom_frame_id: odom_combined
    global_frame_id: map


    tf_broadcast: true
    transform_tolerance: 1.0


    robot_model_type: nav2_amcl::DifferentialMotionModel


    min_particles: 500
    max_particles: 3000


    laser_model_type: likelihood_field

    laser_min_range: 0.15
    laser_max_range: 12.0


    update_min_d: 0.05
    update_min_a: 0.05


    alpha1: 0.1
    alpha2: 0.1
    alpha3: 0.1
    alpha4: 0.1


    do_beamskip: true
    beam_skip_distance: 0.5
    beam_skip_threshold: 0.3
    beam_skip_error_threshold: 0.9