"""
place_manager — named place management for mobile robot navigation.

This is a ROS2 hybrid package. The ``place_manager.srv`` module is
auto-generated by ``rosidl_generate_interfaces`` from the ``srv/`` directory.
"""
