[develop]
script_dir=$base/lib/grounding
[install]
install_scripts=$base/lib/grounding

[options.data_files]
share/ament_index/resource_index/packages = resource/grounding
share/grounding = package.xml
share/grounding/config = grounding/config/grounding_params.yaml
share/grounding/launch = grounding/launch/ground_bringup.launch.py
