from setuptools import find_packages, setup

package_name = 'place_manager'

setup(
    name=package_name,
    version='0.1.0',
    packages=find_packages(exclude=['test']),
    data_files=[],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='sundasheng',
    maintainer_email='sundasheng@todo.todo',
    description='Place Manager — semantic location management for robot navigation',
    license='MIT',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            # Note: In ament_cmake hybrid builds, console_scripts are not
            # auto-generated by ament_python_install_package.
            # The actual executable is installed via scripts/place_manager_node
            # + CMake install(PROGRAMS ...).
            # This entry point is kept for metadata / future pure-ament_python.
            f'{package_name}_node = {package_name}.place_manager_node:main',
        ],
    },
)
